name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       php: [8.4, 8.3, 8.1]
  #       laravel: [12.*, 11.*, 10.*]
  #       stability: [prefer-stable]
  #       include:
  #         - laravel: 12.*
  #           testbench: 10.*
  #         - laravel: 11.*
  #           testbench: 9.*
  #         - laravel: 10.*
  #           testbench: 8.*
  #       exclude:
  #         - laravel: 10.*
  #           php: 8.4
  #         - laravel: 11.*
  #           php: 8.1
  #         - laravel: 12.*
  #           php: 8.1

  #   name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: ${{ matrix.php }}
  #         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
  #         coverage: none

  #     - name: Setup problem matchers
  #       run: |
  #         echo "::add-matcher::${{ runner.tool_cache }}/php.json"
  #         echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

  #     - name: Install dependencies
  #       run: |
  #         composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
  #         composer update --${{ matrix.stability }} --prefer-dist --no-interaction

  #     - name: List Installed Dependencies
  #       run: composer show -D

  #     - name: Execute tests
  #       run: vendor/bin/pest --ci

  install:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GOCPASPACE_HEALTHCHECK_SECRET: secret
    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.3, 8.1]
        laravel: [12, 11, 10]
        exclude:
          - laravel: 10
            php: 8.4
          - laravel: 11
            php: 8.1
          - laravel: 12
            php: 8.1
    name: "Laravel ${{ matrix.laravel }} on PHP${{ matrix.php }}"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install laravel and create temporary repository
        run: |
          composer create-project "laravel/laravel:^${{ matrix.laravel }}.0" .
          composer require spatie/laravel-health gocpa/space-healthcheck:dev-new-version
          php artisan vendor:publish --tag="health-migrations"
          php artisan migrate
          git config --global init.defaultBranch master
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git init
          git add .
          git commit -m "initial commit"
          php artisan health:check --no-notification

      - name: Run Laravel Server
        run: |
          php artisan serve --host=127.0.0.1 --port=8000 &

      - name: Make request to get health
        id: testRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "http://127.0.0.1:8000/space/check"
          method: 'GET'
          customHeaders: '{"Content-Type": "application/json", "x-space-secret-key": "${{ env.GOCPASPACE_HEALTHCHECK_SECRET }}"}'
          retry: 10

      - name: Show Response
        run: |
          echo ${{ steps.testRequest.outputs.response }}
          echo ${{ steps.testRequest.outputs.headers }}
          echo ${{ steps.testRequest.outputs.status }}
          echo ${{ fromJson(steps.testRequest.outputs.response).generatedAt }}

